output_dir: $SCRATCH/cosmoflow-benchmark/cosmoflow-latest-adam

data:
    name: cosmo
    #data_dir: /project/projectdirs/m3363/www/cosmoUniverse_2019_02_4parE/dim128_cube_nT4
    #data_dir: $DW_PERSISTENT_STRIPED_cosmobb/cosmoUniverse_2019_02_4parE/dim128_cube_nT4
    data_dir: /data
    n_train_files: 640
    n_valid_files: 256
    samples_per_file: 64
    sample_shape: [128, 128, 128, 4]
    batch_size: 1
    n_epochs: 40

model:
    name: cosmoflow
    input_shape: [128, 128, 128, 4]
    target_size: 4
    dropout: 0.2

optimizer:
    name: Adam
    lr: 0.0001
    lr_scaling: none

train:
    loss: mse
    metrics: ['mae']
    lr_schedule:
        16: 0.3
        32: 0.333
