output_dir: $SCRATCH/cosmoflow-benchmark/scaling-dummy-n${SLURM_JOB_NUM_NODES}

data:
    name: dummy
    n_train: 64
    n_valid: 0
    shard: true
    sample_shape: [128, 128, 128, 4]
    target_shape: [4]
    batch_size: 1
    n_epochs: 4

model:
    name: cosmoflow_orig
    input_shape: [128, 128, 128, 4]
    target_size: 4
    dropout: 0.2

optimizer:
    name: Adam
    lr: 0.0001
    lr_scaling: none

train:
    loss: mse
    metrics: ['mae']
